config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root :to => 'companies#index'
  resources :accept_conditions, :except => [:show]
  resources :events
  resources :companies do
    resources :checks, :except => [:show]
  end
  resources :datas, :only => [:index]
  resources :screening_process, :only => [:index]
  resources :first_interviews, :only => [:index]
  resources :second_interviews, :only => [:index]
  resources :third_interviews, :only => [:index]
  resources :last_interviews, :only => [:index]
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :company, optional: true

  enum name: { introduction: 0, screening_process: 1, first_interview: 2, second_interview: 3, third_interview: 4, last_interview: 5, talk: 6, other: 7}
  enum is_passed: { no_result: 0, passed: 1, droped: 2 }
  validates :name, {presence: true}
  validates :company_id, {presence: true}
  validates :date, {presence: true}
  validates :is_passed, {presence: true}
  
  def self.next_event?(company)
    Event.where(company_id: company.id).where("date > ?", Date.today).exists?
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: %i[ show edit update destroy ]
  PER_PAGE = 10
  # GET /events or /events.json
  def index
    @events_past = Event.where("date <= ?", Date.today).where(user_id: current_user.id).order(date: "DESC").page(params[:page]).per(PER_PAGE)
    @events = Event.where("date > ?", Date.today).where(user_id: current_user.id).order(date: "ASC").page(params[:page]).per(PER_PAGE)

  end

  # GET /events/1 or /events/1.json
  def show
    if @event.user == current_user
      render "show"
    else
      redirect_to root_path
    end
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
    if @event.user == current_user
      render "edit"
    else
      redirect_to root_path
    end
  end

  # POST /events or /events.json
  def create
    @event = Event.new(event_params)
    @event.user_id = current_user.id
    respond_to do |format|
      if @event.save
        # イベントのステータスで落選に変更されたら、企業のステータスを選考済みに変更
        if @event.is_passed == 'droped'
          company = Company.find(@event.company_id)
          company.is_active = false
          company.save
        end
        format.html { redirect_to @event, notice: "イベントの作成に成功しました。" }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1 or /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
         # イベントのステータスで落選に変更されたら、企業のステータスを選考済みに変更
        if @event.is_passed == 'droped'
          company = Company.find(@event.company_id)
          company.is_active = false
          company.save
        end
        format.html { redirect_to @event, notice: "イベントの更新に成功しました。" }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1 or /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: "イベントの削除に成功しました。" }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def event_params
      params.require(:event).permit(:user_id, :company_id, :name, :date, :is_passed)
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<%= form_with(model: event, local: true) do |form| %>
  <% if event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event.errors.count, "つのエラー") %> が発生し保存できません</h2>
      <ul>
      <% event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    ■ <%= form.label :company_id %><br>
    <%= form.select :company_id, Company.where(user_id: current_user.id).map{|t| [t.name, t.id]}, class: "form-control" %>
  </div>

  <div class="field">
    ■ <%= form.label :name %><br>
    <%= form.select :name, Event.names.keys.map {|k| [I18n.t("enums.event.names.#{k}"), k]}, class: "form-control" %>
  </div>

  <div class="field">
    ■ <%= form.label :date %><br>
    <%= form.datetime_select :date, class: "form-control" %>
  </div>

  <div class="field">
    ■ <%= form.label :is_passed %><br>
    <%= form.select :is_passed, Event.is_passeds.keys.map {|k| [I18n.t("enums.event.is_passeds.#{k}"), k]}, class: "form-control" %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/events/_list.html.erb
<% events .each do |event| %>
  <%= link_to event do %>
    <div class="box_r">
      <div class="row">
        <div class="col-md-4">
          <%= event.company.name %>
        </div>
        <div class="col-md-4 col-xs-8">
          <%= event.company.job %>
        </div>
      </div>
      <div class="row">
        <div class="col-md-4 col-xs-12">
          <%= render 'companies/function', company: Company.find(event.company_id) %>
        </div>
        <div class="col-md-8 col-xs-12 title">
          <p>
            次の選考: <%= render 'companies/event_name', company_event: event %>
            &emsp;<br class="sp_only">日時:  <%= l event.date, format: :long %>&emsp;
          </p>
          <% if event.is_passed == 'no_result' %>
            <p class="count status">
              ステータス未登録
            </p>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
<% end %>

app/views/events/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-12">
      <div class="title">
        <h1><%= link_to '<', @event %></h1>
        <h2>イベント編集</h2>
      </div>
      <hr>

      <%= render 'form', event: @event %>
    </div>
  </div>
</div>

app/views/events/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-12">
      <p id="notice"><%= notice %></p>
      <h2>イベント一覧</h2>
      <hr>
      <div class="center padding_b">
        <%= link_to 'イベントの登録', new_event_path, class: "btn btn-primary w-75" %>
      </div>
      <ul class="nav nav-tabs justify-content-center nav-pills">
        <li class="nav-item">
          <a href="#events" class="nav-link active" data-toggle="tab">イベント</a>
        </li>
        <li class="nav-item">
          <a href="#events_past" class="nav-link" data-toggle="tab">過去のイベント</a>
        </li>
      </ul>
      <div class="tab-content">
        <div id="events" class="tab-pane active">
          <%= render 'list', events: @events %>
        </div>
        <div id="events_past" class="tab-pane">
          <%= render 'list', events: @events_past %>
        </div>
      </div>
      <%= paginate @events %>
    </div>
  </div>
</div>

app/views/events/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-12">
      <div class="title">
        <h1><%= link_to '<', events_path %></h1>
        <h2>イベント登録</h2>
      </div>
      <hr>
      <%= render 'form', event: @event %>
    </div>
  </div>
</div>

app/views/events/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-12">
      <div class="title">
        <h1><%= link_to '<', events_path %></h1>
        <h2>イベント詳細</h2>
      </div>
      <hr>
      <p id="notice"><%= notice %></p>
      <p>
        <strong>企業名：&emsp;&emsp;&emsp;</strong>
        <%= @event.company.name %>
      </p>

      <p>
        <strong>イベント名：&emsp;</strong>
        <%= render 'companies/event_name', company_event: @event %>
      </p>

      <p>
        <strong>日時：&emsp;&emsp;&emsp;&emsp;</strong>
        <%= l @event.date, format: :long %>
      </p>

      <p>
        <strong>ステータス：&emsp;</strong>
        <!--カラム名_i18nが反映されなかったため場合分けで表示-->
        <% if @event.is_passed == "no_result" %>
          -----
        <% elsif @event.is_passed == "passed" %>
          通過
        <% else %>
          落選
        <% end %>
      </p>
      <%= link_to '会社詳細へ',company_path(@event.company_id), class: "btn btn-primary" %>
      <%= link_to '編集', edit_event_path(@event), class: "btn btn-success" %>
      <%= link_to '削除', event_path(@event), method: :delete, data: { confirm: '本当に削除しますか?' }, class: "btn btn-danger" %>
    </div>
  </div>
</div>