config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root :to => 'companies#index'
  resources :accept_conditions, :except => [:show]
  resources :events
  resources :companies do
    resources :checks, :except => [:show]
  end
  resources :datas, :only => [:index]
  resources :screening_process, :only => [:index]
  resources :first_interviews, :only => [:index]
  resources :second_interviews, :only => [:index]
  resources :third_interviews, :only => [:index]
  resources :last_interviews, :only => [:index]
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/company.rb
class Company < ApplicationRecord
  belongs_to :user, optional: true
  has_many :events, dependent: :destroy
  has_many :checks, dependent: :destroy
  enum media: { unselected: 0, mynavi: 1, recnavi: 2, type: 3, doda: 4, green: 5, wantedly: 6, dmm: 7, other: 8 }
  validates :name, {presence: true}

end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: %i[ show edit update destroy ]
  PER_PAGE = 10

  # GET /companies or /companies.json
  def index
    @companies = Company.where(user_id: current_user.id, is_active: true).order(id: "DESC").page(params[:page]).per(PER_PAGE)
    @companies_done = Company.where(user_id: current_user.id, is_active: false).order(id: "DESC").page(params[:page]).per(PER_PAGE)
  end

  # GET /companies/1 or /companies/1.json
  def show
    if @company.user == current_user
      render "show"
    else
      redirect_to root_path
    end
  end

  # GET /companies/new
  def new
    @company = Company.new
  end

  # GET /companies/1/edit
  def edit
    if @company.user == current_user
      render "edit"
    else
      redirect_to root_path
    end
  end

  # POST /companies or /companies.json
  def create
    @company = Company.new(company_params)
    @company.user_id = current_user.id
    @accept_conditions = AcceptCondition.where(user_id: current_user.id)
    respond_to do |format|
      if @company.save
        @accept_conditions.each do |accept_condition|
          check = Check.new
          check.company_id = @company.id
          check.accept_condition_id = accept_condition.id
          check.accept = 'no_evidence'
          check.save
        end
        format.html { redirect_to @company, notice: "企業の作成に成功しました。" }
        format.json { render :show, status: :created, location: @company }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /companies/1 or /companies/1.json
  def update
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to @company, notice: "企業の更新に成功しました。" }
        format.json { render :show, status: :ok, location: @company }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1 or /companies/1.json
  def destroy
    @company.destroy
    respond_to do |format|
      format.html { redirect_to companies_url, notice: "企業の削除に成功しました。" }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def company_params
      params.require(:company).permit(:user_id, :name, :media, :job, :detail, :is_active)
    end
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/_event_name.html.erb
<!--カラム名_i18nが反映されなかったため場合分けで表示-->
<% if company_event.name == 'introduction' %>
  説明会
<% elsif company_event.name == 'screening_process' %>
  書類選考
<% elsif company_event.name == 'first_interview' %>
  一次面接
<% elsif company_event.name == 'second_interview' %>
  二次面接
<% elsif company_event.name == 'third_interview' %>
  三次面接
<% elsif company_event.name == 'last_interview' %>
  最終面接
<% elsif company_event.name == 'talk' %>
  面談
<% elsif company_event.name == 'other' %>
  その他
<% end %>

app/views/companies/_form.html.erb
<%= form_with(model: company, local: true) do |form| %>
  <% if company.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(company.errors.count, "つのエラー") %> が発生し保存できません</h2>
      <ul>
      <% company.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    ■ <%= form.label :name %>
    <%= form.text_field :name, class: "form-control", placeholder: "例）株式会社○○○○" %>
  </div>
  <div class="field">
    ■ <%= form.label :media %><br>
    <%= form.select :media, Company.media.keys.map {|k| [I18n.t("enums.company.medias.#{k}"), k]}, class: "form-control" %>
  </div>
  <div class="field">
    ■ <%= form.label :job %>
    <%= form.text_field :job, class: "form-control", placeholder: "例）サーバーサイドエンジニア" %>
  </div>
  <div class="field">
    ■ <%= form.label :detail %>
    <%= form.text_area :detail, class: "form-control", placeholder: "例）創業：1997年", rows: 10 %>
  </div>
  <div class="field">
    ■ <%= form.label :is_active %><br>
    <%= form.select :is_active ,[['選考中',true],['選考済み',false]] %>
  </div>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/companies/_function.html.erb
<!--志望度チェック計算-->
<!--重要度別に重みを変更-->
<!--重要度：低→重み：1、重要度：中→重み：2、重要度：高→重み：3-->
<% if Check.where(company_id: company.id).exists? %>
  <!--total=current_userが設定した条件の合計-->
  <% total = 0 %>
  <!--point=companyが満たす条件の合計-->
  <% point = 0 %>

  <% AcceptCondition.where(user_id: current_user.id).each do |accept_condition| %>
    <% if accept_condition.importance == 'low' && Check.where(accept_condition_id: accept_condition.id, company_id: company.id).pluck(:accept).first == 'yes' %>
      <% point += 1 %>
      <% total += 1 %>
    <% elsif accept_condition.importance == 'low' %>
      <% total += 1 %>
    <% elsif accept_condition.importance == 'medium' && Check.where(accept_condition_id: accept_condition.id, company_id: company.id).pluck(:accept).first == 'yes' %>
      <% total += 2 %>
      <% point += 2 %>
    <% elsif accept_condition.importance == 'medium' %>
      <% total += 2 %>
    <% elsif accept_condition.importance == 'high' && Check.where(accept_condition_id: accept_condition.id, company_id: company.id).pluck(:accept).first == 'yes' %>
      <% total += 3 %>
      <% point += 3 %>
    <% else %>
      <% total += 3 %>
    <% end %>
  <% end %>
  <p>志望度：<%= 100*point/total %>%</p>
<% else %>
  <p>志望度: 未設定</p>
<% end %>

app/views/companies/_list.html.erb
<% companies.each do |company| %>
  <%= link_to company do %>
    <div class="box_r">
      <div class="row">
        <div class="col-md-4">
          <%= company.name %>
        </div>
        <div class="col-md-4 col-xs-8">
          <%= company.job %>
        </div>
      </div>
      <div class="row">
        <div class="col-md-4 col-xs-12 title">
          <p>
            <%= render 'companies/function', company: company %>&emsp;
          </p>
          <% unless Check.where(company_id: company.id, accept: 0).count == 0 %>
            <p class="count">
              未チェック：<%= Check.where(company_id: company.id, accept: 0).count %>個
            </p>
          <% end %>
        </div>
        <div class="col-md-8 col-xs-12">
          <% if Event.next_event?(company) %>
            <% company_event = Event.where(company_id: company.id).order(date: "ASC").last %>
            <p>
              次の選考:
              <%= render 'companies/event_name', company_event: company_event %>
              &emsp;<br class="sp_only"> 日時:  <%= l company_event.date, format: :long %>
            </p>
          <% else %>
            <p>次の選考:未設定</p>
          <% end %>
        </div>
      </div>
      <div class="row">
        <div class="col-12 padding_b flex">
          <p>
            <% if company.is_active == false %>
              <%= link_to '選考中に変更', company_path(company.id, company: {is_active: true}), method: :put, data: { confirm: '本当に選考中に変更しますか?' }, class: "btn btn-success" %>
            <% else %>
              <%= link_to '選考済みに変更', company_path(company.id, company: {is_active: false}), method: :put, data: { confirm: '本当に選考済みに変更しますか?' }, class: "btn btn-danger" %>
            <% end %>
          </p>
          <% if Event.next_event?(company) == false && company.is_active == true %>
          <p style="margin-left: 10px;">
            <%= link_to '次の選考を追加', new_event_path, class: "btn btn-primary" %>
          </p>
          <% end %>
        </div>
      </div>
     </div>
  <% end %>
<% end %>

app/views/companies/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-12">
      <div class="title">
        <h1><%= link_to '<', @company %></h1>
        <h2><%= @company.name %></h2>
      </div>
      <hr>
      <%= render 'form', company: @company %>
    </div>
  </div>
</div>

app/views/companies/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-12">
      <p id="notice"><%= notice %></p>
      <h2>応募リスト</h2>
      <hr>
      <div class="center padding_b">
        <%= link_to '応募企業の登録', new_company_path, class: "btn btn-primary w-75" %>
      </div>

      <ul class="nav nav-tabs justify-content-center nav-pills">
        <li class="nav-item">
          <a href="#active" class="nav-link active" data-toggle="tab">選考中</a>
        </li>
        <li class="nav-item">
          <a href="#done" class="nav-link" data-toggle="tab">選考終了</a>
        </li>
      </ul>
      <div class="tab-content">
        <div id="active" class="tab-pane active">
          <%= render 'list', companies: @companies %>
        </div>
        <div id="done" class="tab-pane">
          <%= render 'list', companies: @companies_done %>
        </div>
      </div>
      <%= paginate @companies %>
    </div>
  </div>
</div>

app/views/companies/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-12">
      <div class="title">
        <h1><%= link_to '<', companies_path %></h1>
        <h2>企業の登録</h2>
      </div>
      <hr>
      <%= render 'form', company: @company %>
    </div>
  </div>
</div>

app/views/companies/show.html.erb
<% if @company.user_id == current_user.id %>
  <div class="container">
    <div class="row">
      <div class="col-12">
        <p id="notice"><%= notice %></p>
        <div class="title">
          <h1><%= link_to '<', companies_path %></h2>
          <h2><%= @company.name %></h2>
        </div>
        <hr>
        <div class="box_r">
          <div class="row">
            <div class="col-md-4 col-xs-12">
              <p>企業名：<%= @company.name %></p>
            </div>
            <div class="col-md-4 col-xs-12">
              <p>職種：<%= @company.job %></p>
            </div>
            <div class="col-md-4 col-xs-12">
              <p>
                ステータス：
                <% if @company.is_active == true %>
                  選考中
                <% else %>
                  選考済み
                <% end %>
              </p>
            </div>
          </div>
          <div class="row">
            <div class="col-md-4 col-xs-12 title">
              <p><%= render 'function', company: @company %>&emsp;</p>
              <% unless Check.where(company_id: @company.id, accept: 0).count == 0 %>
                <p class="count">
                  未チェック：<%= Check.where(company_id: @company.id, accept: 0).count %>個
                </p>
              <% end %>
            </div>
            <div class="col-md-8 col-xs-12">
              <% if Event.next_event?(@company) %>
                <% @company_event = Event.where(company_id: @company.id).order(date: "ASC").last %>
                <p>
                  次の選考:
                  <%= render 'event_name', company_event: @company_event %>
                  &emsp;<br class="sp_only"> 日時:  <%= l @company_event.date, format: :long %>
                </p>
              <% else %>
                <p>次の選考:未設定</p>
              <% end %>
            </div>
          </div>
        </div>
        <p>
          <!--カラム名_i18nが反映されなかったため場合分けで表示-->
          <strong>応募媒体：</strong>
          <% if @company.media == "unselected" %>
            <p>未選択</p>
          <% elsif @company.media == "mynavi" %>
            <p>マイナビ</p>
          <% elsif @company.media == "recnavi" %>
            <p>リクルート</p>
          <% elsif @company.media == "type" %>
            <p>Type(タイプ)</p>
          <% elsif @company.media == "doda" %>
            <p>doda(デューダ)</p>
          <% elsif @company.media == "green" %>
            <p>green(グリーン)</p>
          <% elsif @company.media == "wantedly" %>
            <p>wantedly(ウォンテッドリー)</p>
          <% elsif @company.media == "dmm" %>
            <p>DMM</p>
          <% elsif @company.media == "other" %>
            <p>その他</p>
          <% end %>
        </p>
        <p><strong>会社メモ</strong></p>
        <p class="box_s">
          <%= safe_join(@company.detail.split("\n"),tag(:br)) %>
        </p>
          <%= link_to '編集', edit_company_path(@company), class: "btn btn-success" %>
          <%= link_to '削除', company_path(@company), method: :delete, data: { confirm: '本当に削除しますか?' }, class: "btn btn-danger" %>
          <% if Check.where(company_id: @company.id).exists? %>
            <%= link_to '志望度チェック確認', company_checks_path(company_id: params[:id]), class: "btn btn-primary" %>
          <% elsif AcceptCondition.where(user_id: current_user.id).exists? %>
            <%= link_to '志望度チェック新規登録', new_company_check_path(company_id: params[:id]), class: "btn btn-primary" %>
          <% else %>
          <% end %>
      </div>
    </div>
  </div>
<% end %>