config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root :to => 'companies#index'
  resources :accept_conditions, :except => [:show]
  resources :events
  resources :companies do
    resources :checks, :except => [:show]
  end
  resources :datas, :only => [:index]
  resources :screening_process, :only => [:index]
  resources :first_interviews, :only => [:index]
  resources :second_interviews, :only => [:index]
  resources :third_interviews, :only => [:index]
  resources :last_interviews, :only => [:index]
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/check.rb
class Check < ApplicationRecord
  belongs_to :company, optional: true
  belongs_to :accept_condition, optional: true
  enum accept: { no_evidence: 0, yes: 1, no: 2 }
end

app/controllers/checks_controller.rb
class ChecksController < ApplicationController
  before_action :set_check, only: %i[ show edit update destroy ]
  before_action :set_company, only: %i[ index new edit create ]
  before_action :set_accept_condition, only: %i[ new edit create ]
  PER_PAGE = 10

  # GET /checks or /checks.json
  def index
    @checks = Check.joins(:accept_condition).where(company_id: params[:company_id]).order(importance: "DESC").page(params[:page]).per(PER_PAGE)
    if Company.find(params[:company_id]).user == current_user
      render "index"
    else
      redirect_to root_path
    end
  end

  # GET /checks/new
  def new
    @check = Check.new
  end

  # GET /checks/1/edit
  def edit
  end

  # POST /checks or /checks.json
  def create
    @check = Check.new(check_params)
    @check.company_id = params[:company_id]
    respond_to do |format|
      if @check.save
        format.html { redirect_to company_checks_path(company_id: params[:company_id]), notice: "志望度チェックの作成に成功しました。" }
        format.json { redirect_to company_checks_path(company_id: params[:company_id]), status: :created, location: @check }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @check.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /checks/1 or /checks/1.json
  def update
    respond_to do |format|
      if @check.update(check_params)
        format.html { redirect_to company_checks_path(company_id: params[:company_id]), notice: "志望度チェックの更新に成功しました。" }
        format.json { render redirect_to company_checks_path(company_id: params[:company_id]), status: :ok, location: @check }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @check.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /checks/1 or /checks/1.json
  def destroy
    @check.destroy
    respond_to do |format|
      format.html { redirect_to checks_url, notice: "志望度チェックの削除に成功しました。" }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_check
      @check = Check.find(params[:id])
    end

    def set_company
      @company = Company.find(params[:company_id])
    end

    def set_accept_condition
      @accept_conditions = AcceptCondition.where(user_id: current_user.id)
    end

    # Only allow a list of trusted parameters through.
    def check_params
      params.require(:check).permit(:company_id, :accept_condition_id, :accept)
    end
end

app/helpers/checks_helper.rb
module ChecksHelper
end

app/views/checks/_form.html.erb
<%= form_with(model: [company,check], local: true) do |form| %>
　<% if check.errors.any? %>
　  <div id="error_explanation">
　    <h2><%= pluralize(check.errors.count, "つのエラー") %> が発生し保存できません</h2>
　    <ul>
　    <% check.errors.full_messages.each do |message| %>
　      <li><%= message %></li>
　    <% end %>
　    </ul>
　  </div>
　<% end %>
　<div class="field">
　  <%= form.label :accept %>
　  <%= form.select :accept, Check.accepts.keys.map {|k| [I18n.t("enums.check.accepts.#{k}"), k]}, class: "form-control" %>
　</div>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/checks/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-12">
      <div class="title">
        <h1><%= link_to '<', company_checks_path(company_id: params[:company_id]) %></h1>
        <h2><%= @company.name %>志望度チェック</h2>
      </div>
      <hr>
      <p>■ <%= @check.accept_condition.content %></p>
      <p><%= render 'form', company: @company, check: @check %></p>
    </div>
  </div>
</div>

app/views/checks/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-12">
      <p id="notice"><%= notice %></p>
      <div class="title">
        <h1><%= link_to '<', company_path(id: params[:company_id]) %></h1>
        <h2><%= @company.name %><br class="sp_only">志望度チェック</h2>
      </div>
      <table class="table">
        <tbody>
          <% @checks.each do |check| %>
            <tr>
              <td><%= check.accept_condition.content %></td>
              <td class="pc_only">
                <!--カラム名_i18nが反映されなかったため場合分けで表示-->
                重要度：
                <% if check.accept_condition.importance =="low" %>
                  低
                <% elsif check.accept_condition.importance =="medium" %>
                  中
                <% else %>
                  高
                <% end %>
              </td>
              <td>
                <!--カラム名_i18nが反映されなかったため場合分けで表示-->
                <% if check.accept == 'no_evidence' %>
                  -----
                <% elsif check.accept == 'yes' %>
                  条件を満たす
                <% else %>
                  条件を満たさない
                <% end %>
              </td>
              <td><%= link_to '編集', edit_company_check_path(company_id: params[:company_id], id: check.id), class: "btn btn-success" %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <%= paginate @checks %>
    </div>
  </div>
</div>

app/views/checks/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-12">
      <div class="title">
        <h1><%= link_to '<', company_path(id: params[:company_id]) %></h1>
        <h2><%= @company.name %>志望度チェック</h2>
      </div>
      <hr>
      <%= render 'form', company: @company, check: @check %>
    </div>
  </div>
</div>