config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root :to => 'companies#index'
  resources :accept_conditions, :except => [:show]
  resources :events
  resources :companies do
    resources :checks, :except => [:show]
  end
  resources :datas, :only => [:index]
  resources :screening_process, :only => [:index]
  resources :first_interviews, :only => [:index]
  resources :second_interviews, :only => [:index]
  resources :third_interviews, :only => [:index]
  resources :last_interviews, :only => [:index]
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Recruit</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/014a69a131.js" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>

  <body>
    <header>
    </header>
    <% flash.each do |message_type, message| %>
      <%= content_tag :div, message, class: message_type %>
    <% end %>
    <main>
      <%= yield %>
      <div class="box"></div>
    </main>
    <footer>
      <ul>
        <% if user_signed_in? %>
          <li>
            <%= link_to companies_path do %>
              <i class="fas fa-pencil-alt"></i><br>
              <span class="font">応募リスト</span>
            <% end %>
          </li>
          <li>
            <%= link_to datas_path do %>
              <i class="fas fa-database"></i><br>
              <span class="font">データ</span>
            <% end %>
          </li>
          <li>
            <%= link_to events_path do %>
              <i class="fas fa-calendar-alt"></i><br>
              <span class="font">イベント一覧</span>
            <% end %>
          </li>
          <li>
            <%= link_to accept_conditions_path do %>
              <i class="fas fa-lightbulb"></i><br>
              <span class="font">条件</span>
            <% end %>
          </li>

          <li>
            <%= link_to destroy_user_session_path, method: :delete do %>
              <i class="fas fa-sign-out-alt"></i><br>
              <span class="font">ログアウト</span>
            <% end %>
          </li>
        <% end %>
      </ul>
    </footer>
  </body>
</html>